# Generated by Django 5.0.6 on 2024-06-21 02:52

import base.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emergency_remove_billing_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AlterField(
            model_name='emergency',
            name='date',
            field=models.DateTimeField(default=base.models.nepal_time_default),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='schedule',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
